export const ALL_LIFE_EVENT_TYPES = [
    { value: "VEHICLE_PURCHASE", label: "Vehicle Purchase", tier: 1 },
    { value: "RENTAL_VERIFICATION", label: "Rental Verification", tier: 1 },
    { value: "ELDERCARE_MANAGEMENT", label: "Eldercare Management", tier: 1 },
    { value: "EDUCATION_FINANCING", label: "Education Financing", tier: 1 },
    { value: "CAREER_TRANSITION", label: "Career Transition", tier: 1 },
    { value: "POSTPARTUM_WELLNESS", label: "Postpartum Wellness", tier: 1 },
    { value: "WORKPLACE_WELLNESS", label: "Workplace Wellness", tier: 1 },
    { value: "PREGNANCY_PREPARATION", label: "Pregnancy Preparation", tier: 1 },
    { value: "CHILD_SCHOOL_TRANSITION", label: "Child School Transition", tier: 1 },
    { value: "WOMEN_DIVORCE_RECOVERY", label: "Women Divorce Recovery", tier: 1 },
    { value: "JOB_ONBOARDING", label: "Job Onboarding", tier: 2 },
    { value: "RELOCATION", label: "Relocation", tier: 2 },
    { value: "MARRIAGE_PLANNING", label: "Marriage Planning", tier: 2 },
    { value: "HOME_PURCHASE", label: "Home Purchase", tier: 2 },
    { value: "BUSINESS_STARTUP", label: "Business Startup", tier: 2 },
    { value: "WOMEN_ENTREPRENEURSHIP", label: "Women Entrepreneurship", tier: 2 },
    { value: "REPATRIATION", label: "Repatriation", tier: 2 },
    { value: "MEDICAL_EMERGENCY", label: "Medical Emergency", tier: 2 },
    { value: "VISA_APPLICATION", label: "Visa Application", tier: 2 },
    { value: "EDUCATIONAL_ENROLLMENT", label: "Educational Enrollment", tier: 2 },
    { value: "WELLNESS_MANAGEMENT", label: "Wellness Management", tier: 3 },
    { value: "PROPERTY_INHERITANCE", label: "Property Inheritance", tier: 3 },
    { value: "HEALTH_INSURANCE", label: "Health Insurance", tier: 3 },
    { value: "DEBT_MANAGEMENT", label: "Debt Management", tier: 3 },
    { value: "CAREER_UPSKILLING", label: "Career Upskilling", tier: 3 },
    { value: "RETIREMENT_PLANNING", label: "Retirement Planning", tier: 3 },
    { value: "FAMILY_RELOCATION", label: "Family Relocation", tier: 3 },
    { value: "INTERNATIONAL_TRAVEL", label: "International Travel", tier: 3 },
    { value: "ADOPTION_PROCESS", label: "Adoption Process", tier: 3 },
    
    // New Globally Relevant Pillars
    { value: "HOME_PURCHASE_PROCESS", label: "Home Purchase Process", tier: 4 },
    { value: "STUDY_ABROAD", label: "Study Abroad", tier: 4 },
    { value: "GRADUATE_STUDIES", label: "Graduate Studies", tier: 4 },
    { value: "PET_ADOPTION", label: "Pet Adoption", tier: 4 },
    { value: "VOLUNTEER_WORK", label: "Volunteer Work", tier: 4 },
    { value: "ESTATE_PLANNING", label: "Estate Planning", tier: 4 },
    { value: "PARENTAL_LEAVE", label: "Parental Leave", tier: 4 },
    { value: "GRIEF_SUPPORT", label: "Grief Support", tier: 4 },
    { value: "TRAVEL_RELOCATION", label: "Travel Relocation", tier: 4 },
    { value: "FREELANCE_SETUP", label: "Freelance Setup", tier: 4 },

    { value: "OTHER", label: "Other", tier: 0 }
];
